In [1]:
from ShallowLearn import LoadData, Training

RasterioIOError: /run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20160711T003712no_transform/6880_T55LCD_20160711T003712no_transform.tiff: No such file or directory

In [2]:
Training

<module 'ShallowLearn.Training' from '/home/ziad/Documents/Github/ShallowLearn/ShallowLearn/Training.py'>

In [3]:
    path_to_hdd = "/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20151204T004052no_transform"
    file_name = "/6880_T55LCD_20151204T004052no_transform.tiff"
    full_path = path_to_hdd + file_name

    data = LoadData.LoadGeoTIFF(full_path).load()

In [4]:
data

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
LoadData.LoadGeoTIFF("")

In [6]:
sl.LoadGeoTIFF()

NameError: name 'sl' is not defined

In [ ]:
dir(sl)

NameError: name 'sl' is not defined

In [7]:
sl

NameError: name 'sl' is not defined

In [4]:
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.decomposition import PCA
from scipy import stats
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler
import glob
import matplotlib.pyplot as plt
from matplotlib import cm
import matplotlib.patches as mpatches
import numpy as np
from sklearn.cluster import OPTICS, cluster_optics_dbscan
import pickle
import pandas as pd

In [10]:
images = []
for image, reef in zip(data.full_path, data.reef):
    if reef == 6880:
        img = LoadData.LoadGeoTIFF(image).load()
        img_shp = img.shape
        img = img.transpose(1, 2, 0).reshape(img_shp[1] * img_shp[2], img_shp[0])
        images.append(img)

In [11]:
images

[array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint16),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 

In [2]:
data ="/home/ziad/Documents/Github/Reef_Sensing_ML/DBs/Clear_Reefs.csv"
# data = LoadData.LoadFromCSV(data)

In [5]:
data = pd.read_csv(data)

In [7]:
import numpy as np

# assume your data is stored in a variable called 'data'
data = np.random.rand(54, 13, 725, 534)

# reshape the data to (X, 13)
X = np.prod(data.shape[:-1])  # compute the new number of rows
data_reshaped = data.reshape(X, 13)

# use the reshaped data as needed
print(data_reshaped.shape)

ValueError: cannot reshape array of size 271779300 into shape (508950,13)

In [22]:
data.load()

/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20160611T004002no_transform/6459_T55LCD_20160611T004002no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20160721T004002no_transform/6459_T55LCD_20160721T004002no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170507T003711no_transform/6459_T55LCD_20170507T003711no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170606T004001no_transform/6459_T55LCD_20170606T004001no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170716T004001no_transform/6459_T55LCD_20170716T004001no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170815T003711no_transform/6459_T55LCD_20170815T003711no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170825T004001no_transform/6459_T55LCD_20170825T004001no_transform.tiff
/run/media/ziad/Expansion/Clipped_Reefs_By_Image/T55LCD_20170924T003701no_transform/6459_T55LCD_2

[array([[[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        ...,
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]],
 
        [[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],

In [19]:
LoadData.LoadFromCSV()

AttributeError: module 'ShallowLearn.LoadData' has no attribute 'LoadFromCSV'